# Generated by Django 4.1.1 on 2022-10-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=254, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Correo')),
                ('nombre2', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('tipo_usuario', models.CharField(choices=[('universitario', 'Uni'), ('Normal', 'Nor')], max_length=13)),
                ('universidad', models.CharField(blank=True, max_length=80, null=True)),
                ('facultad', models.CharField(blank=True, max_length=50, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('semestre', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
