# Generated by Django 4.1.1 on 2022-10-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=254, unique=True, verbose_name='Nombre'),
        ),
    ]
