# Generated by Django 4.1.1 on 2022-09-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('password', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('universitario', 'Uni'), ('Normal', 'Nor')], max_length=13)),
                ('universidad', models.CharField(max_length=80, null=True)),
                ('facultad', models.CharField(max_length=50, null=True)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('semestre', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('identificacion', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
