# Generated by Django 4.1.1 on 2022-10-08 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0005_grupo_universitario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uni', to='Web2.universitario'),
        ),
    ]
