# Generated by Django 4.1.1 on 2022-10-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0006_grupo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='tipo',
        ),
    ]
