# Generated by Django 4.1.1 on 2022-10-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0007_remove_grupo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
