# Generated by Django 4.1.1 on 2022-10-09 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web2', '0008_alter_grupo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='propuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
                ('diapostivas', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
