# Generated by Django 4.1.1 on 2022-10-09 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web2', '0011_alter_grupo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrupo', to=settings.AUTH_USER_MODEL),
        ),
    ]
