# Generated by Django 4.1.1 on 2022-10-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0012_alter_grupo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitario',
            name='lider',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
