# Generated by Django 4.1.1 on 2022-10-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0016_alter_propuesta_diapostivas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='diapostivas',
            field=models.FileField(upload_to='diapositivas/'),
        ),
    ]
