# Generated by Django 4.1.1 on 2022-10-12 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web2', '0018_relacion_relacion_web2_relaci_from_us_49dd7d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='migrupo', to=settings.AUTH_USER_MODEL),
        ),
    ]
