# Generated by Django 4.1.1 on 2022-10-13 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web2', '0019_alter_grupo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='seguir',
            field=models.ManyToManyField(blank=True, related_name='seguir', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrupo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Relacion',
        ),
    ]
