# Generated by Django 4.1.1 on 2022-10-16 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0022_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Web2.propuesta'),
        ),
    ]
