# Generated by Django 4.1.1 on 2022-10-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0023_propuesta_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='Descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='diapostivas',
            field=models.FileField(null=True, upload_to='diapositivas/'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
