# Generated by Django 4.1.1 on 2022-10-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0025_alter_propuesta_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='padre',
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='Descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='diapostivas',
            field=models.FileField(upload_to='diapositivas/'),
        ),
        migrations.AlterField(
            model_name='propuesta',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
