# Generated by Django 4.1.1 on 2022-10-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0030_comentarios_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='user',
        ),
    ]
