# Generated by Django 4.1.1 on 2022-10-18 03:31

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0032_lider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
