# Generated by Django 4.1.1 on 2022-10-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0033_alter_propuesta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dirigido', to='Web2.propuesta'),
            preserve_default=False,
        ),
    ]
