# Generated by Django 4.1.1 on 2022-10-19 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web2', '0034_contacto_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuesta',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
