# Generated by Django 4.1.1 on 2022-10-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web2', '0035_propuesta_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='usuario',
            new_name='user',
        ),
    ]
